version: "3.7"
networks:
  merginmaps:

services:
  db:
    image: postgres:14
    container_name: merginmaps-db
    restart: always
    networks:
      - merginmaps
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./mergin_db:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: merginmaps-redis
    restart: always
    networks:
      - merginmaps
  server:
    image: lutraconsulting/merginmaps-backend:2023.2.0
    container_name: merginmaps-server
    restart: always
    user: 901:999
    volumes:
      - ./projects:/data
    env_file:
      - .prod.env
    depends_on:
      - db
      - redis
    networks:
      - merginmaps
  web:
    image: lutraconsulting/merginmaps-frontend:2023.2.0
    container_name: merginmaps-web
    restart: always
    depends_on:
      - server
    links:
      - db
    networks:
      - merginmaps
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    #command: certonly --staging --webroot -w /var/www/certbot --force-renewal --email mail@philippe-guigue.de -d waldplan.de --agree-tos
    #command: certonly -vvv --staging --break-my-certs  --webroot --webroot-path=/var/www/certbot --email philippe.guigue@posteo.net --agree-tos --no-eff-email --force-renewal -d mergin.waldplan.de -d www.mergin.waldplan.de
    command: certonly --webroot --break-my-certs --webroot-path=/var/www/certbot --email philippe.guigue@posteo.net --agree-tos --no-eff-email --force-renewal -d mergin.waldplan.de -d www.mergin.waldplan.de
  proxy:
    image: nginx
    container_name: merginmaps-proxy
    restart: always
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./projects:/data  # map data dir to host
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - merginmaps
